-- Inserta todos los países reconocidos en la tabla travel.country (nombres en español)
INSERT INTO travel.country (name) VALUES ('Afganistán');
INSERT INTO travel.country (name) VALUES ('Albania');
INSERT INTO travel.country (name) VALUES ('Argelia');
INSERT INTO travel.country (name) VALUES ('Andorra');
INSERT INTO travel.country (name) VALUES ('Angola');
INSERT INTO travel.country (name) VALUES ('Antigua y Barbuda');
INSERT INTO travel.country (name) VALUES ('Argentina');
INSERT INTO travel.country (name) VALUES ('Armenia');
INSERT INTO travel.country (name) VALUES ('Australia');
INSERT INTO travel.country (name) VALUES ('Austria');
INSERT INTO travel.country (name) VALUES ('Azerbaiyán');
INSERT INTO travel.country (name) VALUES ('Bahamas');
INSERT INTO travel.country (name) VALUES ('Baréin');
INSERT INTO travel.country (name) VALUES ('Bangladés');
INSERT INTO travel.country (name) VALUES ('Barbados');
INSERT INTO travel.country (name) VALUES ('Bielorrusia');
INSERT INTO travel.country (name) VALUES ('Bélgica');
INSERT INTO travel.country (name) VALUES ('Belice');
INSERT INTO travel.country (name) VALUES ('Benín');
INSERT INTO travel.country (name) VALUES ('Bután');
INSERT INTO travel.country (name) VALUES ('Bolivia');
INSERT INTO travel.country (name) VALUES ('Bosnia y Herzegovina');
INSERT INTO travel.country (name) VALUES ('Botsuana');
INSERT INTO travel.country (name) VALUES ('Brasil');
INSERT INTO travel.country (name) VALUES ('Brunéi');
INSERT INTO travel.country (name) VALUES ('Bulgaria');
INSERT INTO travel.country (name) VALUES ('Burkina Faso');
INSERT INTO travel.country (name) VALUES ('Burundi');
INSERT INTO travel.country (name) VALUES ('Cabo Verde');
INSERT INTO travel.country (name) VALUES ('Camboya');
INSERT INTO travel.country (name) VALUES ('Camerún');
INSERT INTO travel.country (name) VALUES ('Canadá');
INSERT INTO travel.country (name) VALUES ('República Centroafricana');
INSERT INTO travel.country (name) VALUES ('Chad');
INSERT INTO travel.country (name) VALUES ('Chile');
INSERT INTO travel.country (name) VALUES ('China');
INSERT INTO travel.country (name) VALUES ('Colombia');
INSERT INTO travel.country (name) VALUES ('Comoras');
INSERT INTO travel.country (name) VALUES ('República Democrática del Congo');
INSERT INTO travel.country (name) VALUES ('República del Congo');
INSERT INTO travel.country (name) VALUES ('Costa Rica');
INSERT INTO travel.country (name) VALUES ('Costa de Marfil');
INSERT INTO travel.country (name) VALUES ('Croacia');
INSERT INTO travel.country (name) VALUES ('Cuba');
INSERT INTO travel.country (name) VALUES ('Chipre');
INSERT INTO travel.country (name) VALUES ('Chequia');
INSERT INTO travel.country (name) VALUES ('Dinamarca');
INSERT INTO travel.country (name) VALUES ('Yibuti');
INSERT INTO travel.country (name) VALUES ('Dominica');
INSERT INTO travel.country (name) VALUES ('República Dominicana');
INSERT INTO travel.country (name) VALUES ('Ecuador');
INSERT INTO travel.country (name) VALUES ('Egipto');
INSERT INTO travel.country (name) VALUES ('El Salvador');
INSERT INTO travel.country (name) VALUES ('Guinea Ecuatorial');
INSERT INTO travel.country (name) VALUES ('Eritrea');
INSERT INTO travel.country (name) VALUES ('Estonia');
INSERT INTO travel.country (name) VALUES ('Esuatini');
INSERT INTO travel.country (name) VALUES ('Etiopía');
INSERT INTO travel.country (name) VALUES ('Fiyi');
INSERT INTO travel.country (name) VALUES ('Finlandia');
INSERT INTO travel.country (name) VALUES ('Francia');
INSERT INTO travel.country (name) VALUES ('Gabón');
INSERT INTO travel.country (name) VALUES ('Gambia');
INSERT INTO travel.country (name) VALUES ('Georgia');
INSERT INTO travel.country (name) VALUES ('Alemania');
INSERT INTO travel.country (name) VALUES ('Ghana');
INSERT INTO travel.country (name) VALUES ('Grecia');
INSERT INTO travel.country (name) VALUES ('Granada');
INSERT INTO travel.country (name) VALUES ('Guatemala');
INSERT INTO travel.country (name) VALUES ('Guinea');
INSERT INTO travel.country (name) VALUES ('Guinea-Bisáu');
INSERT INTO travel.country (name) VALUES ('Guyana');
INSERT INTO travel.country (name) VALUES ('Haití');
INSERT INTO travel.country (name) VALUES ('Honduras');
INSERT INTO travel.country (name) VALUES ('Hungría');
INSERT INTO travel.country (name) VALUES ('Islandia');
INSERT INTO travel.country (name) VALUES ('India');
INSERT INTO travel.country (name) VALUES ('Indonesia');
INSERT INTO travel.country (name) VALUES ('Irán');
INSERT INTO travel.country (name) VALUES ('Irak');
INSERT INTO travel.country (name) VALUES ('Irlanda');
INSERT INTO travel.country (name) VALUES ('Israel');
INSERT INTO travel.country (name) VALUES ('Italia');
INSERT INTO travel.country (name) VALUES ('Jamaica');
INSERT INTO travel.country (name) VALUES ('Japón');
INSERT INTO travel.country (name) VALUES ('Jordania');
INSERT INTO travel.country (name) VALUES ('Kazajistán');
INSERT INTO travel.country (name) VALUES ('Kenia');
INSERT INTO travel.country (name) VALUES ('Kiribati');
INSERT INTO travel.country (name) VALUES ('Corea del Norte');
INSERT INTO travel.country (name) VALUES ('Corea del Sur');
INSERT INTO travel.country (name) VALUES ('Kosovo');
INSERT INTO travel.country (name) VALUES ('Kuwait');
INSERT INTO travel.country (name) VALUES ('Kirguistán');
INSERT INTO travel.country (name) VALUES ('Laos');
INSERT INTO travel.country (name) VALUES ('Letonia');
INSERT INTO travel.country (name) VALUES ('Líbano');
INSERT INTO travel.country (name) VALUES ('Lesoto');
INSERT INTO travel.country (name) VALUES ('Liberia');
INSERT INTO travel.country (name) VALUES ('Libia');
INSERT INTO travel.country (name) VALUES ('Liechtenstein');
INSERT INTO travel.country (name) VALUES ('Lituania');
INSERT INTO travel.country (name) VALUES ('Luxemburgo');
INSERT INTO travel.country (name) VALUES ('Madagascar');
INSERT INTO travel.country (name) VALUES ('Malaui');
INSERT INTO travel.country (name) VALUES ('Malasia');
INSERT INTO travel.country (name) VALUES ('Maldivas');
INSERT INTO travel.country (name) VALUES ('Malí');
INSERT INTO travel.country (name) VALUES ('Malta');
INSERT INTO travel.country (name) VALUES ('Islas Marshall');
INSERT INTO travel.country (name) VALUES ('Mauritania');
INSERT INTO travel.country (name) VALUES ('Mauricio');
INSERT INTO travel.country (name) VALUES ('México');
INSERT INTO travel.country (name) VALUES ('Micronesia');
INSERT INTO travel.country (name) VALUES ('Moldavia');
INSERT INTO travel.country (name) VALUES ('Mónaco');
INSERT INTO travel.country (name) VALUES ('Mongolia');
INSERT INTO travel.country (name) VALUES ('Montenegro');
INSERT INTO travel.country (name) VALUES ('Marruecos');
INSERT INTO travel.country (name) VALUES ('Mozambique');
INSERT INTO travel.country (name) VALUES ('Birmania');
INSERT INTO travel.country (name) VALUES ('Namibia');
INSERT INTO travel.country (name) VALUES ('Nauru');
INSERT INTO travel.country (name) VALUES ('Nepal');
INSERT INTO travel.country (name) VALUES ('Países Bajos');
INSERT INTO travel.country (name) VALUES ('Nueva Zelanda');
INSERT INTO travel.country (name) VALUES ('Nicaragua');
INSERT INTO travel.country (name) VALUES ('Níger');
INSERT INTO travel.country (name) VALUES ('Nigeria');
INSERT INTO travel.country (name) VALUES ('Macedonia del Norte');
INSERT INTO travel.country (name) VALUES ('Noruega');
INSERT INTO travel.country (name) VALUES ('Omán');
INSERT INTO travel.country (name) VALUES ('Pakistán');
INSERT INTO travel.country (name) VALUES ('Palaos');
INSERT INTO travel.country (name) VALUES ('Palestina');
INSERT INTO travel.country (name) VALUES ('Panamá');
INSERT INTO travel.country (name) VALUES ('Papúa Nueva Guinea');
INSERT INTO travel.country (name) VALUES ('Paraguay');
INSERT INTO travel.country (name) VALUES ('Perú');
INSERT INTO travel.country (name) VALUES ('Filipinas');
INSERT INTO travel.country (name) VALUES ('Polonia');
INSERT INTO travel.country (name) VALUES ('Portugal');
INSERT INTO travel.country (name) VALUES ('Catar');
INSERT INTO travel.country (name) VALUES ('Rumanía');
INSERT INTO travel.country (name) VALUES ('Rusia');
INSERT INTO travel.country (name) VALUES ('Ruanda');
INSERT INTO travel.country (name) VALUES ('San Cristóbal y Nieves');
INSERT INTO travel.country (name) VALUES ('Santa Lucía');
INSERT INTO travel.country (name) VALUES ('San Vicente y las Granadinas');
INSERT INTO travel.country (name) VALUES ('Samoa');
INSERT INTO travel.country (name) VALUES ('San Marino');
INSERT INTO travel.country (name) VALUES ('Santo Tomé y Príncipe');
INSERT INTO travel.country (name) VALUES ('Arabia Saudita');
INSERT INTO travel.country (name) VALUES ('Senegal');
INSERT INTO travel.country (name) VALUES ('Serbia');
INSERT INTO travel.country (name) VALUES ('Seychelles');
INSERT INTO travel.country (name) VALUES ('Sierra Leona');
INSERT INTO travel.country (name) VALUES ('Singapur');
INSERT INTO travel.country (name) VALUES ('Eslovaquia');
INSERT INTO travel.country (name) VALUES ('Eslovenia');
INSERT INTO travel.country (name) VALUES ('Islas Salomón');
INSERT INTO travel.country (name) VALUES ('Somalia');
INSERT INTO travel.country (name) VALUES ('Sudáfrica');
INSERT INTO travel.country (name) VALUES ('Sudán del Sur');
INSERT INTO travel.country (name) VALUES ('España');
INSERT INTO travel.country (name) VALUES ('Sri Lanka');
INSERT INTO travel.country (name) VALUES ('Sudán');
INSERT INTO travel.country (name) VALUES ('Surinam');
INSERT INTO travel.country (name) VALUES ('Suecia');
INSERT INTO travel.country (name) VALUES ('Suiza');
INSERT INTO travel.country (name) VALUES ('Siria');
INSERT INTO travel.country (name) VALUES ('Taiwán');
INSERT INTO travel.country (name) VALUES ('Tayikistán');
INSERT INTO travel.country (name) VALUES ('Tanzania');
INSERT INTO travel.country (name) VALUES ('Tailandia');
INSERT INTO travel.country (name) VALUES ('Timor Oriental');
INSERT INTO travel.country (name) VALUES ('Togo');
INSERT INTO travel.country (name) VALUES ('Tonga');
INSERT INTO travel.country (name) VALUES ('Trinidad y Tobago');
INSERT INTO travel.country (name) VALUES ('Túnez');
INSERT INTO travel.country (name) VALUES ('Turquía');
INSERT INTO travel.country (name) VALUES ('Turkmenistán');
INSERT INTO travel.country (name) VALUES ('Tuvalu');
INSERT INTO travel.country (name) VALUES ('Uganda');
INSERT INTO travel.country (name) VALUES ('Ucrania');
INSERT INTO travel.country (name) VALUES ('Emiratos Árabes Unidos');
INSERT INTO travel.country (name) VALUES ('Reino Unido');
INSERT INTO travel.country (name) VALUES ('Estados Unidos');
INSERT INTO travel.country (name) VALUES ('Uruguay');
INSERT INTO travel.country (name) VALUES ('Uzbekistán');
INSERT INTO travel.country (name) VALUES ('Vanuatu');
INSERT INTO travel.country (name) VALUES ('Ciudad del Vaticano');
INSERT INTO travel.country (name) VALUES ('Venezuela');
INSERT INTO travel.country (name) VALUES ('Vietnam');
INSERT INTO travel.country (name) VALUES ('Yemen');
INSERT INTO travel.country (name) VALUES ('Zambia');
INSERT INTO travel.country (name) VALUES ('Zimbabue');
